[package]
name = "server"
version = "0.1.0"
authors = ["Master0r0 <m.sarahgreywolf@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.20", features = ["full"] }

mineonline_api = {path = "..\\mineonline_api"}
mc_packets = {path = "..\\mc_packets"}